# Generated by Django 5.2.17 on 2026-09-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'jogo',
                'verbose_name_plural': 'jogos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('download_url', models.URLField(help_text='URL externa para download ou página de download do item.', max_length=500, verbose_name='link para download')),
                ('image_url', models.URLField(help_text='URL externa da imagem de exemplo/capa do item.', max_length=500, verbose_name='link da imagem')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.category', verbose_name='categoria')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.game', verbose_name='jogo')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='items_item_slug_d94d1c_idx'), models.Index(fields=['game', 'category'], name='items_item_game_id_c66535_idx'), models.Index(fields=['is_published', '-created_at'], name='items_item_is_publ_cf4fa5_idx')],
            },
        ),
    ]
