# Generated by Django 5.2.17 on 2026-09-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL externa da imagem de exemplo do post.', max_length=500, verbose_name='link da imagem')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Ordem da imagem na exibição.', verbose_name='posição')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'imagem do post',
                'verbose_name_plural': 'imagens do post',
                'ordering': ['position', 'id'],
            },
        ),
    ]
